from __future__ import annotations

import argparse
import importlib.metadata
import json
import shutil
import socket
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from .config import AppConfig, example_config_text, load_config
from .server import create_app
from .version import __version__


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def codex_config_text(config: AppConfig) -> str:
    base_url = f"http://{config.server.host}:{config.server.port}/v1"
    context_window = config.model.max_prompt_tokens + config.model.min_response_tokens
    compact_limit = max(512, int(config.model.max_prompt_tokens * 0.75))
    auth_line = ""
    if config.security.api_token_env:
        auth_line = f"env_key = {_toml_string(config.security.api_token_env)}\n"
    return f'''# Generated by npu-codex. Keep this in a dedicated CODEX_HOME.
model = {_toml_string(config.model.id)}
model_provider = "npu_codex"
model_context_window = {context_window}
model_auto_compact_token_limit = {compact_limit}

[model_providers.npu_codex]
name = "Local Intel NPU bridge"
base_url = {_toml_string(base_url)}
wire_api = "responses"
requires_openai_auth = false
supports_websockets = false
request_max_retries = 1
stream_max_retries = 1
stream_idle_timeout_ms = 600000
{auth_line}'''


def _write_text(path: Path, content: str, *, force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"refusing to overwrite existing file: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def _package_version(name: str) -> str | None:
    try:
        return importlib.metadata.version(name)
    except importlib.metadata.PackageNotFoundError:
        return None


def _port_available(host: str, port: int) -> bool:
    family = socket.AF_INET6 if ":" in host else socket.AF_INET
    with socket.socket(family, socket.SOCK_STREAM) as sock:
        try:
            sock.bind((host, port))
        except OSError:
            return False
    return True


def doctor_report(config: AppConfig) -> dict[str, Any]:
    checks: list[dict[str, Any]] = []

    def add(name: str, ok: bool, detail: Any, *, critical: bool = True) -> None:
        checks.append({"name": name, "ok": ok, "detail": detail, "critical": critical})

    add("python", sys.version_info >= (3, 11), sys.version.split()[0])
    add(
        "model_directory",
        config.model.backend == "mock" or config.model.path.is_dir(),
        str(config.model.path),
    )
    xml_files = list(config.model.path.glob("*.xml")) if config.model.path.is_dir() else []
    add(
        "openvino_ir",
        config.model.backend == "mock" or bool(xml_files),
        [file.name for file in xml_files[:8]],
    )
    add(
        "listen_port",
        _port_available(config.server.host, config.server.port),
        f"{config.server.host}:{config.server.port}",
        critical=False,
    )

    codex_path = shutil.which("codex")
    codex_version: str | None = None
    if codex_path:
        try:
            result = subprocess.run(
                [codex_path, "--version"],
                text=True,
                capture_output=True,
                timeout=10,
                check=False,
            )
            codex_version = (result.stdout or result.stderr).strip()
        except Exception as exc:
            codex_version = f"error: {exc}"
    add("codex_cli", bool(codex_path), codex_version or "not found", critical=False)

    if config.model.backend == "openvino":
        ov_version = _package_version("openvino")
        genai_version = _package_version("openvino-genai")
        add("openvino_package", ov_version is not None, ov_version or "not installed")
        add("openvino_genai_package", genai_version is not None, genai_version or "not installed")
        devices: list[str] = []
        device_error: str | None = None
        if ov_version:
            try:
                import openvino as ov  # type: ignore[import-not-found]

                devices = [str(value).upper() for value in ov.Core().available_devices]
            except Exception as exc:
                device_error = f"{type(exc).__name__}: {exc}"
        requested = config.model.device.upper()
        device_ok = requested in devices or (
            config.model.allow_cpu_fallback and "CPU" in devices
        )
        add(
            "inference_device",
            device_ok,
            {"requested": requested, "available": devices, "error": device_error},
        )

    failed_critical = [check for check in checks if check["critical"] and not check["ok"]]
    return {
        "ok": not failed_critical,
        "version": __version__,
        "backend": config.model.backend,
        "checks": checks,
    }


def _print_doctor(report: dict[str, Any]) -> None:
    print(f"NPU Codex doctor {report['version']} ({report['backend']})")
    for check in report["checks"]:
        marker = "OK" if check["ok"] else ("WARN" if not check["critical"] else "FAIL")
        print(f"[{marker:4}] {check['name']}: {check['detail']}")
    print("Result:", "ready for this configuration" if report["ok"] else "critical checks failed")


def _smoke_test(config: AppConfig) -> dict[str, Any]:
    url = f"http://{config.server.host}:{config.server.port}/v1/responses"
    payload = json.dumps(
        {
            "model": config.model.id,
            "input": "Reply with a brief bridge status message.",
            "stream": False,
        }
    ).encode()
    request = urllib.request.Request(
        url,
        data=payload,
        method="POST",
        headers={"Content-Type": "application/json", "Host": f"{config.server.host}:{config.server.port}"},
    )
    try:
        with urllib.request.urlopen(request, timeout=120) as response:
            body = json.loads(response.read().decode())
            return {"ok": response.status == 200, "status": response.status, "response": body}
    except urllib.error.HTTPError as exc:
        return {
            "ok": False,
            "status": exc.code,
            "response": exc.read().decode("utf-8", "replace"),
        }
    except Exception as exc:
        return {"ok": False, "error": f"{type(exc).__name__}: {exc}"}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="npu-codex",
        description="Local Responses API bridge for Codex and Intel NPU inference.",
    )
    parser.add_argument("--version", action="version", version=__version__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init", help="write an example bridge configuration")
    init_parser.add_argument("--output", type=Path, default=Path("config.local.toml"))
    init_parser.add_argument("--mock", action="store_true")
    init_parser.add_argument("--force", action="store_true")

    serve_parser = subparsers.add_parser("serve", help="run the local bridge")
    serve_parser.add_argument("--config", type=Path, default=Path("config.local.toml"))

    doctor_parser = subparsers.add_parser("doctor", help="check the local installation")
    doctor_parser.add_argument("--config", type=Path, default=Path("config.local.toml"))
    doctor_parser.add_argument("--json", action="store_true")

    codex_parser = subparsers.add_parser(
        "write-codex-config", help="write a dedicated Codex config.toml"
    )
    codex_parser.add_argument("--config", type=Path, default=Path("config.local.toml"))
    codex_parser.add_argument(
        "--output", type=Path, default=Path(".codex-local/config.toml")
    )
    codex_parser.add_argument("--force", action="store_true")

    smoke_parser = subparsers.add_parser("smoke-test", help="call the running bridge")
    smoke_parser.add_argument("--config", type=Path, default=Path("config.local.toml"))
    smoke_parser.add_argument("--json", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        if args.command == "init":
            _write_text(args.output, example_config_text(mock=args.mock), force=args.force)
            print(f"Wrote {args.output}")
            return 0

        config = load_config(args.config)
        if args.command == "serve":
            import uvicorn

            app = create_app(config)
            uvicorn.run(
                app,
                host=config.server.host,
                port=config.server.port,
                log_level=config.server.log_level,
                access_log=False,
                server_header=False,
            )
            return 0
        if args.command == "doctor":
            report = doctor_report(config)
            if args.json:
                print(json.dumps(report, ensure_ascii=False, indent=2))
            else:
                _print_doctor(report)
            return 0 if report["ok"] else 1
        if args.command == "write-codex-config":
            _write_text(args.output, codex_config_text(config), force=args.force)
            print(f"Wrote {args.output}")
            if config.security.api_token_env:
                print(f"Set {config.security.api_token_env} before starting Codex.")
            return 0
        if args.command == "smoke-test":
            report = _smoke_test(config)
            if args.json:
                print(json.dumps(report, ensure_ascii=False, indent=2))
            else:
                print("OK" if report.get("ok") else "FAIL", report)
            return 0 if report.get("ok") else 1
    except Exception as exc:
        print(f"error: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 1
    return 2
